###
POST http://localhost:3000/medico/cadastrar
Content-Type: application/json

{
    "nome": "Franciele Silveira",
    "crm": "123",
    "especialidade": "ortopedia"
}

###
GET http://localhost:3000/medico/buscar/456

###
GET http://localhost:3000/medico/listar

###
PUT http://localhost:3000/medico/alterar
Content-Type: application/json

{
    "nome": "Franciele do Carmo Silveira",
    "crm": "123",
    "especialidade": "ortopedia"
}

###
DELETE http://localhost:3000/medico/remover/123